# Задача 1. Создать класс Money для работы с денежными суммами. Число должно быть представлено двумя полями: для рублей и для копеек. Копейки при выводе на экран   олжна быть отделена от целой части запятой. Реализовать сложение, вычитание, деление сумм, деление суммы на дробное число, умножение на дробное число и операции сравнения.

In [1]:
class Money:

    """
    Класс для работы с денежными суммами
    
    Атрибуты:
            balance: начальный баланс кошелька. Принимает на вход данные в формате float (например 160,70)
            
    Методы: balance(self) - геттер,  balance(self, money :float) - сеттер
            addition(self, money :float = 0) - сложение баланса с суммой money - возвращает: сумму
            subtraction(self, money :float = 0) - вычитание из баланса суммы money - возвращает: разницу
            multiplication(self, multiplier :float = 1) - умножение баланса на мноэитель multiplier - возвращает: произведение
            division(self, multiplier :float = 1) - деление баланса на мноэитель multiplier - возвращает: результат деления
    """

    def __init__(self, balance :float = 0.0):
        """
        Инициализация матрицы.

        Параметры:
            balance: float - цифровое значение баланса в формате float (например 160,70).
        """
        
        # Переводим рубли с копейками просто в копейки
        self._balance = int(100*balance)

    @property
    def balance(self):

        """
        Геттер для запроса на отображения баланса.

        """
        print(f'Остаток денег на счету составляет: {self._balance // 100},{self._balance % 100} рублей')



    @balance.setter
    def balance(self, money :float):
        """
        Сеттер для установки значения баланса (на всякий случай)

        """
        self._balance = money

    
    def addition(self, money :float = 0):

        """
        Метод для увеличения баланса

        Параметры:
        money - сумма которая добавляется к балансу

        """
        self._balance += int(100*money)

    
    def subtraction(self, money :float = 0):

        """
        Метод для уменьшения баланса

        Параметры:
        money - сумма которая вычитается из баланса

        """
        
        if self._balance < int(100*money):
            print(f'Операция невозможна. Остаток денег на счету составляет всего: {self._balance // 100},{self._balance % 100} рублей')
        else:
            self._balance -= int(100*money)


    def multiplication(self, multiplier :float = 1):

        """
        Метод для умножения баланса

        Параметры:
        multiplier - сумма на которую умножается баланс

        """
        if multiplier <=0:
            print(f'Операция не имеет физ смысла если множитель <=0')
        else:
            self._balance = int(self._balance*multiplier)

    # деление сумм
    def division(self, multiplier :float = 1):

        """
        Метод для деления баланса

        Параметры:
        multiplier - сумма на которую делится баланс

        """
        
        if multiplier <= 0:
            print(f'Операция невозможна. Нельзя делить на 0, а деление на отрицательное число не имеет смысла')
        else:
            self._balance = int(self._balance / multiplier)
    

In [2]:
my_card = Money(1016.97)
my_card.balance

my_card.addition(50.70)
my_card.balance

my_card.subtraction(200.11)
my_card.balance

my_card.multiplication(2.3)
my_card.balance

my_card.division(3.1)
my_card.balance

my_card.division(0)
my_card.multiplication(0)

Остаток денег на счету составляет: 1016,97 рублей
Остаток денег на счету составляет: 1067,67 рублей
Остаток денег на счету составляет: 867,56 рублей
Остаток денег на счету составляет: 1995,38 рублей
Остаток денег на счету составляет: 643,67 рублей
Операция невозможна. Нельзя делить на 0, а деление на отрицательное число не имеет смысла
Операция не имеет физ смысла если множитель <=0


# Задача 2. Создать класс матрица и реализовать алгоритмы математических операций над матрицами (сложение друг с другом, умножение на скалярную величину).

In [3]:
# Решение задачи без использования Numpy

# Импортируем абстрактный класс и метод

from abc import ABC, abstractmethod
from typing import Union, List

class Matrix(ABC):
    """
    Абстрактный класс для операций с матрицами.
    
    Атрибуты:
        data (List[List[Union[int, float]]]): Данные матрицы (двумерный список).
        rows (int): Количество строк в матрице.
        cols (int): Количество столбцов в матрице.

    Методы:
        add(self, other): Сложение матриц.
        scalar_multiply(self, scalar): Умножение матрицы на скаляр.
    """

    def __init__(self, data: List[List[Union[int, float]]]):
        """
        Инициализация матрицы.

        Параметры:
            data (List[List[Union[int, float]]]): Двумерный список, представляющий матрицу.
        """
        self.data: List[List[Union[int, float]]] = data

        # Записываем в переменные кл-во строк и столбцов
        
        self.rows: int = len(data)
        self.cols: int = len(data[0]) if data else 0

    @abstractmethod
    def add(self, other: "Matrix") -> "Matrix":
        """
        Абстрактный метод для сложения матриц.

        Параметры:
            other (Matrix): Вторая матрица для сложения.

        Возвращает:
            Matrix: Результат сложения матриц.
        """
        pass

    @abstractmethod
    def scalar_multiply(self, scalar: Union[int, float]) -> "Matrix":
        """
        Абстрактный метод для умножения матрицы на скаляр.

        Параметры:
            scalar (Union[int, float]): Скаляр, на который нужно умножить матрицу.

        Возвращает:
            Matrix: Результат умножения матрицы на скаляр.
        """
        pass

class MatrixOperations(Matrix):

    """
    Класс для непосредственной рабоы с матрицами (наследуется от своего абстратного класса Matrix)
    
    Методы: add(self, other)  -  метод для сложения матриц 
            scalar_multiply(self, scalar) метод для умнолжения матрицы на скаляр 
    """
    
    def add(self, other):
        if self.rows != other.rows or self.cols != other.cols:
            print("Матрицы должны быть одного размера!")
            return
        result = [[self.data[i][j] + other.data[i][j] for j in range(self.cols)] for i in range(self.rows)]
        return MatrixOperations(result)

    def scalar_multiply(self, scalar):
        result = [[self.data[i][j] * scalar for j in range(self.cols)] for i in range(self.rows)]
        return MatrixOperations(result)


In [4]:

m1 = MatrixOperations([[1, 2], [3, 4]])
m2 = MatrixOperations([[5, 6], [7, 8]])

m3 = m1.add(m2)
print(m3.data)  

m4 = m1.scalar_multiply(2)
print(m4.data)  


[[6, 8], [10, 12]]
[[2, 4], [6, 8]]


In [5]:
# Решение задачи c использованием Numpy

import numpy as np
from abc import ABC, abstractmethod
from typing import Union


class MatrixNumpy(ABC):
    """
    Абстрактный класс для операций с матрицами, использующий NumPy.
    
    Атрибуты:
        data (np.ndarray): Двумерный массив, представляющий матрицу.
        rows (int): Количество строк.
        cols (int): Количество столбцов.
    """

    def __init__(self, data: Union[list[list[Union[int, float]]], np.ndarray]):
        """
        Инициализация матрицы.

        Параметры:
            data (Union[list[list[Union[int, float]]], np.ndarray]): Двумерные данные для матрицы.
        """
        self.data: np.ndarray = np.array(data)  # Преобразуем входные данные в массив NumPy

        # Записываем в переменные кл-во строк и столбцов
        
        self.rows: int = self.data.shape[0]   
        self.cols: int = self.data.shape[1]

    @abstractmethod
    def add(self, other: "Matrix") -> "Matrix":
        """
        Абстрактный метод для сложения матриц.

        Параметры:
            other (Matrix): Матрица для сложения.

        Возвращает:
            Matrix: Новая матрица как результат сложения.
        """
        pass

    @abstractmethod
    def scalar_multiply(self, scalar: Union[int, float]) -> "Matrix":
        """
        Абстрактный метод для умножения матрицы на скаляр.

        Параметры:
            scalar (Union[int, float]): Скаляр для умножения.

        Возвращает:
            Matrix: Новая матрица как результат умножения.
        """
        pass


class MatrixOperationsNumpy(MatrixNumpy):
    """
    Класс для операций с матрицами, основанный на использовании NumPy(наследуется от своего абстратного класса MatrixNumpy)
    Методы: Наследуются из родительского класса MatrixNumpy
    """

    def add(self, other: "Matrix"):
        if self.data.shape != other.data.shape:
            print("Матрицы должны быть одного размера!")
            return
        result = self.data + other.data  # Используем NumPy для сложения
        return MatrixOperationsNumpy(result)

    def scalar_multiply(self, scalar: Union[int, float]):
        result = self.data * scalar  # Умножение массива NumPy на скаляр
        return MatrixOperationsNumpy(result)


In [6]:
m5 = MatrixOperationsNumpy([[1, 2], [3, 4]])
m6 = MatrixOperationsNumpy([[5, 6], [7, 8]])

m7 = m5.add(m6)
print(m3.data)  

m8 = m5.scalar_multiply(2)
print(m8.data)  


[[6, 8], [10, 12]]
[[2 4]
 [6 8]]


# Задача 3. необходимо реализовать набор операций над одномерными и двумерными структурами. Каждой структуре необходимо выделить свой класс. При описании классов использовать принципы ООП.

In [7]:
# Решение без использования numpy

from __future__ import annotations
from abc import ABC, abstractmethod
from typing import Self

class Structure(ABC):

    """
    Абстрактный класс для операций с структурами (одномерными и двумерными).

    Методы:
        add(self, other): Сложение структур.
        scalar_multiply(self, scalar): Умножение структур на скаляр.
        subtraction(self, other: Structure) Вычитания структур
        multiply(self, other: Structure) Умножение структур
        divide(self, other: Structure) Деление структур
    """

    
    @abstractmethod
    def add(self, other: Structure)-> Self:

        """
        Абстрактный метод для сложения структур.

        Параметры:
            other (Structure): Другая структура для сложения.

        Возвращает:
            Self: Новая матрица как результат сложения.
        """
        
        pass

    @abstractmethod
    def scale(self, scalar: Union[int, float])-> Self:

        """
        Абстрактный метод для умножения структуры на скаляр.

        Параметры:
            scalar (Union[int, float]): Скаляр для умножения.

        Возвращает:
            Self: Новая структура как результат умножения.
        """
        
        pass

    @abstractmethod
    def subtraction(self, other: Structure) -> Self:
        """
        Абстрактный метод для вычитания структур.
        Параметры:
             other: Structure - другая структура для сложения

        Возвращает:
            Self: Новая структура как результат вычитания.
        """
        pass

    @abstractmethod
    def multiply(self, other: Structure) -> Self:
        """
        Абстрактный метод для перемножения структур.
        Параметры:
             other: Structure - другая структура для сложения

        Возвращает:
            Self: Новая структура как результат умножения.
        """
        pass

    @abstractmethod
    def divide(self, other: Structure) -> Self:
        """
        Абстрактный метод для деления структур.
        Параметры:
             other: Structure - другая структура для сложения

        Возвращает:
            Self: Новая структура как результат деления.
        """
        pass

class OneDimensionalStructure(Structure):

    """
    Класс для операций с одномерными структурами

    Методы: Наследуются из родительского класса Structure
    """
    
    def __init__(self, data):

        """
        Инициализация матрицы.

        Параметры:
            data (List[List[Union[int, float]]]): Двумерный список, представляющий матрицу.
        """

        try:
            if not isinstance(data, list):
                raise TypeError("Данные должны быть списком!")
            self.data = data
            
        except TypeError:
            print("Данные должны быть списком!")

    def add(self, other: "OneDimensionalStructure")-> "OneDimensionalStructure":

        try:
            if len(self.data) != len(other.data):
                raise ValueError("Длины одномерных структур должны совпадать!")
            result = [self.data[i] + other.data[i] for i in range(len(self.data))]
            return OneDimensionalStructure(result)
            
        except TypeError:
            print("Длины одномерных структур должны совпадать!")

    
    def scale(self, scalar: Union[int, float])-> "Structure":
        
        result = [x * scalar for x in self.data]
        return OneDimensionalStructure(result)
        

    def subtraction(self, other: "OneDimensionalStructure") -> "OneDimensionalStructure":

        try:
            if len(self.data) != len(other.data):
                raise ValueError("Длины одномерных структур должны совпадать!")
                
            result = [self.data[i] - other.data[i] for i in range(len(self.data))]
            return OneDimensionalStructure(result)
            
        except ValueError:
            print("Длины одномерных структур должны совпадать!")

    
    def multiply(self, other: "OneDimensionalStructure") -> "OneDimensionalStructure":
         
        try:
            if len(self.data) != len(other.data):
                raise ValueError("Длины одномерных структур должны совпадать!")
            result = [self.data[i] * other.data[i] for i in range(len(self.data))]
            return OneDimensionalStructure(result)
            
        except ValueError:
            print("Длины одномерных структур должны совпадать!")

    
    def divide(self, other: "OneDimensionalStructure") -> "OneDimensionalStructure":

        try:
            if len(self.data) != len(other.data):
                raise ValueError("Длины одномерных структур должны совпадать!")
            
            # Проверка на деление на ноль
            if 0 in other.data:
                raise ZeroDivisionError("Деление на ноль невозможно!")
            
            result = [self.data[i] / other.data[i] for i in range(len(self.data))]
            return OneDimensionalStructure(result)
            
        except ValueError:
            print("Длины одномерных структур должны совпадать!")
        except ZeroDivisionError:
            print("Деление на ноль невозможно!")

class TwoDimensionalStructure(Structure):

    """
    Класс для операций с двухмерными структурами

    Методы: Наследуются из родительского класса Structure
    """
    
    def __init__(self, data):

        """
        Инициализация матрицы.

        Параметры:
            data (List[List[Union[int, float]]]): Двумерный список, представляющий матрицу.
        """
        self.data = data

        # Записываем в переменные кл-во строк и столбцов
        
        self.rows = len(data)
        self.cols = len(data[0]) if data else 0

    
    def add(self, other: TwoDimensionalStructure) -> Self:

        try:
            if self.rows != other.rows or self.cols != other.cols:
                raise ValueError("Размеры двумерных структур должны совпадать!")
            result = [[self.data[i][j] + other.data[i][j] for j in range(self.cols)] for i in range(self.rows)]
            return TwoDimensionalStructure(result)
            
        except TypeError:
            print("Размеры двумерных структур должны совпадать!")
        

    def scale(self, scalar: Union[int, float])-> Self:
        
        result = [[x * scalar for x in row] for row in self.data]
        return TwoDimensionalStructure(result)

    
    def subtraction(self, other: TwoDimensionalStructure) -> Self:

        try:
            if self.rows != other.rows or self.cols != other.cols:
                raise ValueError("Размеры двумерных структур должны совпадать!")
                
            result = [[self.data[i][j] - other.data[i][j] for j in range(self.cols)] for i in range(self.rows)]
            return TwoDimensionalStructure(result)
            
        except ValueError:
            print("Размеры двумерных структур должны совпадать!")

            
    def multiply(self, other: TwoDimensionalStructure) -> Self:

        try:
            if self.cols != other.rows:
                raise ValueError("Количество столбцов первой матрицы должно совпадать с количеством строк второй матрицы!")
    
            # Создаем результирующую матрицу размера (rows_1 x cols_2)
            result = [[
                sum(self.data[i][k] * other.data[k][j] for k in range(self.cols))
                for j in range(other.cols)
            ] for i in range(self.rows)]
    
            return TwoDimensionalStructure(result)
            
        except ValueError:
            print("Количество столбцов первой матрицы должно совпадать с количеством строк второй матрицы!")

    
    def divide(self, other: TwoDimensionalStructure) -> Self:

        try:
            if self.rows != other.rows or self.cols != other.cols:
                raise ValueError("Размеры двумерных структур должны совпадать!")
                
            # Проверка на деление на ноль
            for row in other.data:
                if any(el == 0 for el in row):
                    raise ZeroDivisionError("Деление на ноль невозможно!")
            
            result = [[self.data[i][j] / other.data[i][j] for j in range(self.cols)] for i in range(self.rows)]
            return TwoDimensionalStructure(result)
            
        except (ValueError, ZeroDivisionError) as e:
            print(e)




In [8]:
v1 = OneDimensionalStructure([1, 2, 3])
v2 = OneDimensionalStructure([4, 5, 6])

v3 = v1.add(v2)
print("Сложение одномерных структур:", v3.data)

v4 = v1.scale(2)
print("Умножение одномерной структуры на скаляр:", v4.data)

v5 = v1.subtraction(v2)
print("Вычитание одномерных структур:", v5.data)

v6 = v1.multiply(v2)
print("умножением одномерных структур:",v6.data)  

# Деление
v7 = v1.divide(v2)
print("Деление одномерных структур:",v7.data)  


# Двумерные структуры
m1 = TwoDimensionalStructure([[1, 2], [3, 4]])
m2 = TwoDimensionalStructure([[5, 6], [7, 8]])

m3 = m1.add(m2)
print("Сложение двумерных структур:\n", m3.data)

m4 = m1.scale(2)
print("Умножение двумерной структуры на скаляр:\n", m4.data)

m5 = m1.subtraction(m2)
print("Вычитание двумерных структур:\n", m5.data)

m6 = m1.multiply(m2)
print("умножением одномерных структур:\n",m6.data)  

# Деление
m7 = m1.divide(m2)
print("Деление одномерных структур:\n",m7.data)  

Сложение одномерных структур: [5, 7, 9]
Умножение одномерной структуры на скаляр: [2, 4, 6]
Вычитание одномерных структур: [-3, -3, -3]
умножением одномерных структур: [4, 10, 18]
Деление одномерных структур: [0.25, 0.4, 0.5]
Сложение двумерных структур:
 [[6, 8], [10, 12]]
Умножение двумерной структуры на скаляр:
 [[2, 4], [6, 8]]
Вычитание двумерных структур:
 [[-4, -4], [-4, -4]]
умножением одномерных структур:
 [[19, 22], [43, 50]]
Деление одномерных структур:
 [[0.2, 0.3333333333333333], [0.42857142857142855, 0.5]]


In [9]:
# Решение c использованием numpy


import numpy as np
from abc import ABC, abstractmethod
from typing import Union


class StructureNumpy(ABC):
    """
    Абстрактный класс для операций с структурами (одномерными и двумерными).

    Методы:
        add(self, other): Сложение структур.
        scalar_multiply(self, scalar): Умножение структур на скаляр.
        subtraction(self, other: StructureNumpy) Вычитания структур
        multiply(self, other: StructureNumpy) Умножение структур
        divide(self, other: StructureNumpy) Деление структур
    """

    @abstractmethod
    def add(self, other: StructureNumpy) -> Self:
        """
        Абстрактный метод для сложения структур.
        Параметры:
             other: StructureNumpy - другая структура для сложения

        Возвращает:
            Self: Новая структура как результат сложения.

        """
        pass

    @abstractmethod
    def scale(self, scalar: Union[int, float]) -> Self:
        """
        Абстрактный метод для умножения структуры на скаляр.
        Параметры:
             scalar: Union[int, float] - число на которое мы умножаем исходную матрицу
        Возвращает:
            Self: Новая структура как результат сложения.
        """
        pass

    @abstractmethod
    def subtraction(self, other: StructureNumpy) -> Self:
        """
        Абстрактный метод для вычитания структур.
        Параметры:
             other: StructureNumpy - другая структура для сложения

        Возвращает:
            StructureNumpy: Новая структура как результат вычитания.
        """
        pass

    @abstractmethod
    def multiply(self, other: StructureNumpy) -> Self:
        """
        Абстрактный метод для перемножения структур.
        Параметры:
             other: StructureNumpy - другая структура для сложения

        Возвращает:
            Self: Новая структура как результат умножения.
        """
        pass

    @abstractmethod
    def divide(self, other: StructureNumpy) -> Self:
        """
        Абстрактный метод для деления структур.
        Параметры:
             other: StructureNumpy - другая структура для сложения

        Возвращает:
            Self: Новая структура как результат деления.
        """
        pass


class OneDimensionalStructureNumpy(StructureNumpy):
    """
    Класс для операций с одномерными структурами на основе NumPy.
    """

    def __init__(self, data: Union[list[Union[int, float]], np.ndarray]):
        """
        Инициализация одномерной структуры.

        Параметры:
            data (Union[list[Union[int, float]], np.ndarray]): Одномерные данные.
        """
        self.data = np.array(data)  # Преобразуем данные в массив NumPy

    def add(self, other: OneDimensionalStructureNumpy) -> Self:

        try:
            
            if self.data.shape != other.data.shape:
                raise ValueError("Длины одномерных структур должны совпадать!")
                
            result = self.data + other.data
            return OneDimensionalStructureNumpy(result)
            
        except ValueError:
            print("Длины одномерных структур должны совпадать!")
            
    def scale(self, scalar: Union[int, float]) -> Self:
        
        result = self.data * scalar
        return OneDimensionalStructureNumpy(result)

    def subtraction(self, other: OneDimensionalStructureNumpy) -> Self:

        try:
            
            if self.data.shape != other.data.shape:
                raise ValueError("Длины одномерных структур должны совпадать!")
                
            result = self.data - other.data
            return OneDimensionalStructureNumpy(result)
            
        except ValueError:
            print("Длины одномерных структур должны совпадать!")

    def multiply(self, other: OneDimensionalStructureNumpy) -> Self:
         
        try:
            if self.data.shape != other.data.shape:
                raise ValueError("Длины одномерных структур должны совпадать!")
            result = self.data * other.data
            return OneDimensionalStructureNumpy(result)
        except ValueError:
            print("Длины одномерных структур должны совпадать!")
        
    def divide(self, other: OneDimensionalStructureNumpy) -> Self:

        try:
            if self.data.shape != other.data.shape:
                raise ValueError("Длины одномерных структур должны совпадать!")
            if np.any(other.data == 0):  # Проверка на деление на ноль
                raise ZeroDivisionError("Деление на ноль невозможно!")
            result = self.data / other.data
            return OneDimensionalStructureNumpy(result)
            
        except ValueError:
            print("Длины одномерных структур должны совпадать!")
        except ZeroDivisionError:
            print("Деление на ноль невозможно!")


class TwoDimensionalStructureNumpy(StructureNumpy):
    """
    Класс для операций с двумерными структурами на основе NumPy.
    """

    def __init__(self, data: Union[list[list[Union[int, float]]], np.ndarray]):
        """
        Инициализация двумерной структуры.

        Параметры:
            data (Union[list[list[Union[int, float]]], np.ndarray]): Двумерные данные.
        """
        self.data = np.array(data)  # Преобразуем данные в массив NumPy
        self.rows, self.cols = self.data.shape  # Запоминаем размеры

    def add(self, other: TwoDimensionalStructureNumpy) -> Self:

        try:
            if self.data.shape != other.data.shape:
                raise ValueError("Размеры двумерных структур должны совпадать!")
                
            result = self.data + other.data
            return TwoDimensionalStructureNumpy(result)
            
        except ValueError:
            print("Размеры двумерных структур должны совпадать!")

    def scale(self, scalar: Union[int, float]) -> Self:
        result = self.data * scalar
        return TwoDimensionalStructureNumpy(result)

    def subtraction(self, other: TwoDimensionalStructureNumpy) -> Self:

        try:
            if self.data.shape != other.data.shape:
                raise ValueError("Размеры двумерных структур должны совпадать!")
                
            result = self.data - other.data
            return TwoDimensionalStructureNumpy(result)
            
        except ValueError:
            print("Размеры двумерных структур должны совпадать!")

    def multiply(self, other: TwoDimensionalStructureNumpy) -> Self:

        try:
            if self.cols != other.rows:
                raise ValueError("Количество столбцов первой матрицы должно совпадать с количеством строк второй матрицы!")
            result = self.data @ other.data  # Матрицы умножаются с помощью оператора @
            return TwoDimensionalStructureNumpy(result)
            
        except ValueError:
            print("Количество столбцов первой матрицы должно совпадать с количеством строк второй матрицы!")

    def divide(self, other: TwoDimensionalStructureNumpy) -> Self:

        try:
            if self.data.shape != other.data.shape:
                raise ValueError("Размеры двумерных структур должны совпадать!")
            if np.any(other.data == 0):  # Проверка на деление на ноль
                raise ZeroDivisionError("Деление на ноль невозможно!")
            result = self.data / other.data  # Поэлементное деление
            return TwoDimensionalStructureNumpy(result)
            
        except ValueError:
            print("Размеры матриц должны совпадать!")
        except ZeroDivisionError:
            print("Деление на ноль невозможно!")

   


In [10]:
vec1 = OneDimensionalStructureNumpy([1, 2, 3])
vec2 = OneDimensionalStructureNumpy([4, 5, 6])

vec3 = vec1.add(vec2)
print("Сложение одномерных структур:", vec3.data)

vec4 = vec1.scale(2)
print("Умножение одномерной структуры на скаляр:", vec4.data)

vec5 = vec1.subtraction(vec2)
print("Вычитание одномерных структур:", vec5.data)

vec6 = vec1.multiply(vec2)
print("умножением одномерных структур:",vec6.data)  

# Деление
vec7 = vec1.divide(vec2)
print("Деление одномерных структур:",vec7.data)  


# Двумерные структуры
mat1 = TwoDimensionalStructureNumpy([[1, 2], [3, 4]])
mat2 = TwoDimensionalStructureNumpy([[5, 6], [7, 8]])

mat3 = mat1.add(mat2)
print("Сложение двумерных структур:\n", mat3.data)

mat4 = mat1.scale(2)
print("Умножение двумерной структуры на скаляр:\n", mat4.data)

mat5 = mat1.subtraction(mat2)
print("Вычитание двумерных структур:\n", mat5.data)

mat6 = mat1.multiply(mat2)
print("умножением одномерных структур:\n",mat6.data)  

# Деление
mat7 = mat1.divide(mat2)
print("Деление одномерных структур:\n",mat7.data)  

Сложение одномерных структур: [5 7 9]
Умножение одномерной структуры на скаляр: [2 4 6]
Вычитание одномерных структур: [-3 -3 -3]
умножением одномерных структур: [ 4 10 18]
Деление одномерных структур: [0.25 0.4  0.5 ]
Сложение двумерных структур:
 [[ 6  8]
 [10 12]]
Умножение двумерной структуры на скаляр:
 [[2 4]
 [6 8]]
Вычитание двумерных структур:
 [[-4 -4]
 [-4 -4]]
умножением одномерных структур:
 [[19 22]
 [43 50]]
Деление одномерных структур:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]
